apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-portfolio
  name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dextermontero/manifest.git
    targetRevision: HEAD
    path: ui-portfolio/staging
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true