apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-portfolio-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-portfolio
  template:
    metadata:
      labels:
        app: ui-portfolio
    spec:
      containers:
      - name: ui-portfolio-container
        image: dextermontero/ui-portfolio:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP