apiVersion: v1
kind: Service
metadata:
  name: ui-portfolio-service
spec:
  selector:
    app: ui-portfolio
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30790
  type: NodePort
