apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-portfolio-development
spec:
  selector:
    matchLabels:
      app: ui-portfolio
  replicas: 2
  template:
    metadata:
      labels:
        app: ui-portfolio
    spec:
      containers:
      - name: ui-portfolio-container
        image: dextermontero/ui-portfolio:latest
        ports:
        - containerPort: 9090