apiVersion: v1
kind: Service
metadata:
  name: ui-portfolio-service
spec:
  selector:
    app: ui-portfolio
  ports:
  - port: 80              # Exposing port 80 on the service (optional: choose based on your needs)
    targetPort: 3000       # Ensure the container is listening on this port
    nodePort: 30080        # External port to expose the service
  type: NodePort
