apiVersion: autoScaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ui-portfolio-hpa
spec:
  scaleTargetRef:
  apiVersion: v1
  kind: Deployment
  name: ui-portfolio
  minReplicas: 2
  maxreplicas: 5
  metrics:
  - type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 50